environments:
  production:
  local:

repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus-node-exporter
  chart: prometheus-community/prometheus-node-exporter
  version: 1.11.1
  values:
  - ./config/prometheus-node-exporter-values.yaml.gotmpl
